name: Go

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [stable, oldstable]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install FUSE (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse

      - name: Install fuse-t (macOS)
        if: runner.os == 'macOS'
        run: brew install fuse-t

      - run: go mod download

      - name: Test
        run: go test -short -timeout 15m ./...
